### ISSUE TITLE
refactor(dmss): refactor blueprint for `system/SIMOS/Application` to remove the unecessary attributes

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-storage-service#270]
The `Application.json` should look similar to this:

```yaml
name: 'something'
description: 'something'
label: 'some thing'
```
