### ISSUE TITLE
feature: cross data source entity references

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-storage-service#337]
Today, an entity with an storage uncontained child will reference it with only the "_id". Like so:

```yaml
type: WorkflowDS/Blueprints/Task
applicationInput:
  _id: 9229e1f3-e94d-4cde-9fb6-a08031b0b04a
  name: exampleAppInput
```

There is no information in which data source the "exampleAppInput" resides. So if it's not the same as the parent. We get a "404".

Suggestion A:
Include data source id in the reference.

```yaml
type: WorkflowDS/Blueprints/Task
applicationInput:
  _id: some_dataSource/9229e1f3-e94d-4cde-9fb6-a08031b0b04a
  name: exampleAppInput
```

Suggestion B:
Update the "system/SIMOS/Reference" to include data source.

```yaml
type: WorkflowDS/Blueprints/Task
applicationInput:
  _id: 9229e1f3-e94d-4cde-9fb6-a08031b0b04a
  _data_source_: some_dataSource  
  name: exampleAppInput
```

Tasks

- [ ] Add demo example for remote entity @eoaksnes 
- [x] ~Use lookup id and create a complete reference that is returned in the document so that it is possible to know what data source to use @soofstad~ **Not doing**
- [ ] Update save method to use the complete reference to store in correct data source

Also issue in #339 
https://github.com/equinor/data-modelling-storage-service/issues/381
